# Generated by Django 5.0.6 on 2024-06-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('tema', models.TextField(default='')),
                ('autor', models.TextField()),
                ('isbn', models.TextField()),
                ('editorial', models.TextField()),
                ('resumen', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='libros')),
                ('cantidad', models.IntegerField(blank=True, default=1, null=True)),
                ('anio', models.TextField(default='2000')),
                ('edad', models.TextField(default='confirmar rango')),
            ],
        ),
    ]
